### PR TITLE
examples without password

### PR DESCRIPTION
**Pull request by petervanderstok**

### CODE REVIEW

**Comment by csosto-pk** [comment]
What was wrong with the previous examples?

**Comment by petervanderstok** [comment]
I used a password on the examples and that made disassembly difficult
for the pkcs8 part.
I removed the password in the examples and redid them.

Peter
Panos K. schreef op 2019-09-04 18:26:

> What was wrong with the previous examples? 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/SanKumar2015/EST-coaps/pull/149?email_source=notifications&amp;email_token=ADCZGQJQ7VANKWOYCL2B3UDQH7ORVA5CNFSM4ITPUMJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD54FFDQ#issuecomment-527979150
[2]

**Comment by csosto-pk** [comment]
That applies to /skg. 
But why did the /crt response change?

**Comment by petervanderstok** [comment]
I removed the password in all examples, regenerated them and put hem in
github

Any problems?

Peter
Panos K. schreef op 2019-09-06 22:08:

> That applies to /skg.
> But why did the /crt response change? 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/SanKumar2015/EST-coaps/pull/149?email_source=notifications&amp;email_token=ADCZGQO5K4XUTMHSTHMVSRLQIK2EBA5CNFSM4ITPUMJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6D5TPI#issuecomment-528996797
[2]

**Comment by csosto-pk** [comment]
No. I vetted the new tests and I didn't find any issues.

**Pull request merged**
